### ISSUE TITLE
Safety: SQL statements shouldn't be insertable from text box

### ISSUE THREAD

**Issue by meriteller** [martinuiga/UT_SoftwareProject2018#52]
For safety reasons have to make sure that users would not be able to insert for example SQL statements through text box answer option.
Time estimation: 10h

**Comment by martinuiga** [comment]
https://wordpress.stackexchange.com/questions/25947/wpdb-insert-do-i-need-to-prepare-against-sql-injection

According to that if we use insert() then we are OK.
